//SE INICIA CON LA EXPLICACIÓN DE LOS METODOS DE CADENAS   
//-------------------------------------------------------------------------------------------------
let cadena = "Gallinotas";
let cadena2= "cadena";


//CONCAT SE ENCARGA DE JUNTAR DOS CADENAS DE TEXTO Y RETORNAR UNA NUEVA
let resultado=cadena.concat(" Hermosas");
document.write(resultado);

//STARSWITH: SI UNA CADENA COMIENZA CON LOS CARACTERES DE OTRA CADENA
//DEVUELVE TRUE, SINO DEVUELVE FALSE

let resultadoStar= cadena.startsWith(cadena2);
document.write(resultadoStar);

//ENDSWITH: SI LA CADENA TERMINA CON LOS CARACTERES DE OTRA CADEA
//DEVUELVE TRUE, SINO DEVUELVE FALSE

//INCLUDE: SI UNA CADENA SE ENCUENTRA DENTRO DE OTRA CADENA
//DEVUELVE TRUE, SINO DEVUELVE FALSE

let resultadoInclude= cadena.includes(cadena2);
document.write(resultadoInclude);
//-------------------------------------------------------------------------------------------------
//INDEXOF: FUNCIONA IGUAL QUE EL INCLUDE SOLO QUE DEVUELVE EL INDICE DONDE SE
//ENCUENTRA LA PALABRA REPETIDA

//-------------------------------------------------------------------------------------------------
//LASTINDEXOF: FUNCIONA PARECIDO AL INDEXOF SOLO QUE DEVUELVE LA ULTIMA PALABRA
//QUE SE REPITE EN CASO DE QUE HAYA VARIAS PALABRAS REPETIDAS

//-------------------------------------------------------------------------------------------------

/*PADSTART: RELLENA LA CADENA SELECCIONADA CON LOS CARACTERES DESEADOS */
//SE ENCARGA DE LLENAR DE ESE CARACTER HASTA QUE CUMPLA CON LA CANTIDAD DE
//ESPACIOS QUE SE ESPECIFIQUE
let resultadoPad= cadena.padStart(20,"a");
document.write(resultadoPad);

//PADEND: RELLENA LA CADENA SELECCIONADA CON LOS CARACTERES DESEADOS


//REPEAT: DEVUELVE LA MISMA CADENA PERO REPETIDA LA CANTIDAD DE VECES QUE
//SE ESPECIFIQUE

let resultadoRep= cadena.repeat(3)
//-------------------------------------------------------------------------------------------------

//SPLIT: DIVIDE LA CADENA COMO SE LO PIDAMOS
let cadena3 = "Hola, buenas , tardes";
let resuSplit= cadena3.split(",");
//LA CADENA SE COMVIERTE EN UN ARRAY SEPARANDO LOS VALORES EN LAS ,


//SUBSTRING: DEVUELVE UNA PARTE DE LA CADENA SELECCIONADA
let resulsubString= cadena3.substring(0,2);
//DEVOLVERÁ LOS VALORES QUE SE ENCUENTREN ENTRE EL PRIMER NUMERO Y EL SEGUNDO
//EN ESTE CASO DEVOLVERIA EL ho, YA QUE SE ENCUENTRA ENTRE EL 0 Y EL 2


//TOLOWERCASE: CONVIERTE LA CADENA EN MINUSCULA
//LOUPPERCASE: CONVIERTE LA CADENA EN MAYUSCULA

//TOSTRING: METODO QUE DEVUELVE UNA CADENA QUE REPRESENTA EL OBJETO
//EN CASO DE QUE LA CADENA SEAN NUMEROS, LOS CONVIERTE DE INT A STRING

//TRIM: ELIMINA LOS ESPACIOS EN BLANCO AL PRINCIPIO Y AL FINAL DE LA CADENA
//TRIMEND: ELIMINA LOS ESPACIOS EN BLANCO AL FINAL DE LA CADENA
//TRIMSTART: ELIMINA LOS ESPACIOS EN BLANCO AL INICIO DE LA CADENA
//VALUE: RETORNA EL VALOR PRIMITIVO DE UN OBJETO STRING
